"""add product check scheduling fields

Revision ID: 8e946712104a
Revises: 52770bd03ab0
Create Date: 2026-05-16 01:05:51.739967

"""
from alembic import op
import sqlalchemy as sa
from datetime import UTC, datetime, timedelta


# revision identifiers, used by Alembic.
revision = '8e946712104a'
down_revision = '52770bd03ab0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_checked_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('next_check_at', sa.DateTime(), nullable=True))
        
    products_table = sa.table(
        "products",
        sa.column("next_check_at", sa.DateTime())
    )

    op.execute(
        products_table.update().values(
            next_check_at=datetime.now(UTC) + timedelta(hours=1)
        )
    )

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column(
            'next_check_at',
            existing_type=sa.DateTime(),
            nullable=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('next_check_at')
        batch_op.drop_column('last_checked_at')

    # ### end Alembic commands ###
